[bastion_host]
bastion ansible_host=111.88.248.75

[web]
web-1.ru-central1.internal
web-2.ru-central1.internal

[elastic]
elastic.ru-central1.internal

[zabbix]
zabbix-server ansible_host=130.193.37.5

[kibana]
kibana-server ansible_host=93.77.191.44

[private:children]
web
elastic

[public:children]
bastion_host
zabbix
kibana

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519

[private:vars]
ansible_ssh_common_args=-o ProxyJump=ubuntu@111.88.248.75
