[bastion_host]
bastion ansible_host=93.77.189.131

[web]
web-1.ru-central1.internal
web-2.ru-central1.internal

[elastic]
elastic.ru-central1.internal

[zabbix]
zabbix-server ansible_host=93.77.184.7

[kibana]
kibana-server ansible_host=93.77.183.204

[private:children]
web
elastic

[public:children]
bastion_host
zabbix
kibana

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3

[private:vars]
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyJump=ubuntu@93.77.189.131
